export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  safelist: [
    'dark:bg-[#10192b]',
    'dark:bg-[#17213a]',
    'dark:text-white',
    'dark:text-gray-100',
    'dark:border-gray-700',
    'dark:bg-gray-900',
    'dark:bg-gray-800',
    'dark:bg-gray-700',
    'dark:text-gray-400',
    'dark:text-gray-300',
    'dark:text-gray-200',
    'dark:text-gray-100',
    'dark:shadow-lg',
    'dark:shadow',
    'dark:ring-gray-600',
    'dark:ring-1',
    'dark:border',
    'dark:rounded-lg',
    'dark:rounded',
    'dark:bg-opacity-80',
    'dark:bg-opacity-90',
    'dark:bg-opacity-100',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
